export const ALL_RESTAURANT = 'ALL_RESTAURANT';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const DELETE_COMMENTS = 'DELETE_COMMENTS';
export const ADD_RESTAURANT = 'ADD_RESTAURANT';
export const EDIT_RESTAURANT = 'EDIT_RESTAURANT';
export const DELETE_RESTAURANT = 'DELETE_RESTAURANT';
export const SEARCH_SAGA = 'SEARCH_SAGA';
